replicaCount: 2
image:
  repository: szarkarbaeva/api-app
  tag: latest
service:
  type: LoadBalancer
  port: 80
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi
env:
  NODE_ENV: production
  DB_HOST: mysql
  DB_PORT: "3306"
secret:
  DB_USER: root
  DB_PASSWORD: password