replicaCount: 1

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

mysql:
  rootPassword: "yourStrongPasswordHere"

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi

config:
  sql_mode: "STRICT_ALL_TABLES"
  max_connections: "200"
