apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-config
data:
  custom.cnf: |
    [mysqld]
    sql_mode={{ .Values.config.sql_mode }}
    max_connections={{ .Values.config.max_connections }}
