apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
spec:
  clusterIP: None  # Headless service
  ports:
    - port: 3306
      name: mysql
  selector:
    app: {{ include "mysql.name" . }}
